### ISSUE TITLE
Support NDK min. API version = 19

### ISSUE THREAD

**Issue by bsergean** [getsentry/sentry-android#168]
We still have a lot of users on Android 4.4 (which is quite old ... but lots of people still use it). It shows at around 7% on this [site](https://www.statista.com/statistics/271774/share-of-android-platforms-on-mobile-devices-with-android-os/
).

With my super limited knowledge of the SDK, I believe that it's only the use of libuuid which appeared in sdk 20 that would have to be worked-around to support min version = 19.

Can you explain what is requiring sdk min version 20 for our understanding ?

**Comment by marandaneto** [comment]
@bsergean thanks for trying out our alpha SDK.

do you refer to the NDK support? right now the min. API level is 21 and we are gonna support soon min. API level 16 on.
It's not only about `libuuid`, the problem actually is `dl_iterate_phdr` which is available only >= API level 21.

Our SDK is min. API level 14.

if you are having problems using our SDK when min. API level < 20, try to do this:

https://github.com/getsentry/sentry-android/blob/a9ab35fd9045fc8f24cf5369bbed8ccac1a38f53/sentry-sample/src/main/AndroidManifest.xml#L7-L8

does it help you?

**Comment by bsergean** [comment]
Thanks for the info Manuel. I'll pass down that info to our Android wizards, I'm just a messenger here :)

**Comment by marandaneto** [comment]
@bsergean sure, please let us know if that worked or not, so we either investigate a bit more or close the issue :)

**Comment by bsergean** [comment]
Hey just to reiterate we are stuck with ndk 19 ; but since I always confuse this Android terminology, what I know for sure is that we need to support users on Android 4.4.

I don't know the deal with dl_iterate_phdr / we use breakpad to capture C++ crashes currently and dl_iterate_phdr isn't used there.

**Comment by marandaneto** [comment]
@bsergean hey, ok, let me see if I got it right.

Do you need to support users on Android 4.4 for native crashes or Java/Kotlin crashes?

If you need to support users on Android 4.4 (API 19) for native crashes, this is not possible right now, but we are gonna work on it, the minimum required right now is Android 5.0 (API 21) and sorry about that.

If you need to support users on Android 4.4 for Java/Kotlin crashes, this is already possible even for Android 4.0.1 (API 14).

Could you tell me which sentence matches your problem?

Thanks :)

**Comment by bsergean** [comment]
> On Dec 5, 2019, at 1:49 AM, Manoel Aranda Neto <notifications@github.com> wrote:
> 
> @bsergean <https://github.com/bsergean> hey, ok, let me see if I got it right.
> 
> Do you need to support users on Android 4.4 for native crashes or Java/Kotlin crashes?
> 
> If you need to support users on Android 4.4 (API 19) for native crashes, this is not possible right now, but we are gonna work on it, the minimum required right now is Android 5.0 (API 21) and sorry about that.
> 
This is what we want to support. It's ok and we can wait, we're happy that you guys have a plan to support that.
Thanks for sticking with us !

**Comment by marandaneto** [comment]
@bsergean sure, we will keep you posted, thanks again :)

**Comment by bsergean** [comment]
Btw we aren't likely to adopt the sdk in the short term, so take your time to do things the right way.

We have a lot of bagage / weirdness in our existing setup that we'd like to fix first before we can adopt a 'normal' sentry sdk unfortunately ; things take time.

**Comment by marandaneto** [comment]
@bsergean definitely, meanwhile we are gonna work on it to make things on the right way, feedback is always welcomed btw :)

**Comment by marandaneto** [comment]
hey, @bsergean we took care of it (see #235) and soon it will be released as an RC version :) stay tuned.
minSdkVersion is gonna be 16 yey.

**Comment by bsergean** [comment]
Excellent !

**Comment by marandaneto** [comment]
hey @bsergean we've released a new version and you may try it out https://github.com/getsentry/sentry-android/releases/tag/2.0.0-rc02

as I said, `minSdkVersion` is `16`.

let us know if you find any issue :) thanks.
