### ISSUE TITLE
How to set auth token

### ISSUE THREAD

**Issue by iEAmi** [getsentry/sentry-android#169]

**Comment by HazAT** [comment]
Can you describe a bit more what are you trying to achieve?
Is it about uploading Proguard mapping files?
Are you maybe talking about the DSN?

A description, explaining what the actual problem is, would help us to help you.

**Comment by marandaneto** [comment]
@iEAmi if you refer to the DSN, you may have a look at the docs https://docs.sentry.io/platforms/android/

also possible in our sample.
https://github.com/getsentry/sentry-android/blob/a9ab35fd9045fc8f24cf5369bbed8ccac1a38f53/sentry-sample/src/main/AndroidManifest.xml#L29

does it answer your question? thanks.

**Comment by iEAmi** [comment]
There is no issue in uploading mapping files. because gradle-plugin uses `sentry. properties` and I can set `dsn` and `auth.token`. my issue is in sending events and exceptions. I use self hosted sentry version 9.1.2 and I need to use `auth.token` but I can not set that. 
Now I am using `sentry-android:2.0.0-alpha08`, before that I used version `1.7.28` and everything was ok.

**Comment by marandaneto** [comment]
@iEAmi I see, in order to send error events all we need is a DSN.
as announced, the new SDK is a major bump, which means breaking changes and will require a migration.
Please formulate your question again in order to understand the problem and help you out, thanks :)

**Comment by iEAmi** [comment]
@marandaneto, so Should I change backend config in order works with new android SDK?
If answer is yes how I can do that? 
When an exception sent to server, it response status is 403.

**Comment by marandaneto** [comment]
@iEAmi I think you are mistaking the things.
So here we go:

`auth.token=YOUR_AUTH_TOKEN` (sentry.properties) is used by the Sentry Android Gradle plugin, this has not changed.

The old SDK requires the DSN like this:
`Sentry.init("https://<key>@sentry.io/<project>", ...`  and this is the part that has changed, this is not an authToken, this is called `DSN` and this is set like this in the new SDK:

https://github.com/getsentry/sentry-android/blob/a9ab35fd9045fc8f24cf5369bbed8ccac1a38f53/sentry-sample/src/main/AndroidManifest.xml#L29

does it help you? thanks.

**Comment by iEAmi** [comment]
OK. I understood. So I just need `DSN` in order to send events . I should review my code and check manifest file again. 

Thank you @marandaneto.

**Comment by marandaneto** [comment]
@iEAmi you're welcome, please let me know if that works, so I may close the issue :)

**Comment by marandaneto** [comment]
@iEAmi please reopen or create a new issue if you still have questions/problems.
