### ISSUE TITLE
Is Sentry v.2.0+ published correctly on Maven Repository?

### ISSUE THREAD

**Issue by AndrewVovk** [getsentry/sentry-android#170]
If I change from
implementation 'io.sentry:sentry-android:1.7.28'
to
implementation 'io.sentry:sentry-android:2.0.0-alpha05'
Sentry classes become unavailable in my project.

While trying to figure out a reason, I've compared 
https://repo1.maven.org/maven2/io/sentry/sentry-android/1.7.28/
and
https://repo1.maven.org/maven2/io/sentry/sentry-android/2.0.0-alpha05/
The size of sentry-android-1.7.28-sources.jar is 13439, but sentry-android-2.0.0-alpha05-sources.jar is just size of 261 and doesn't contain any sources.

Is Sentry v.2.0+ published correctly on Maven Repository?

**Comment by marandaneto** [comment]
@AndrewVovk thanks for trying out our alpha SDK.

Yes, we knew that and already fixed it a while ago.
`alpha01` till `alpha07` had problems of having `alpha` on its name and on pom generation which both have been fixed.
Please try our latest alpha version which is `alpha08`

you can have a look at https://github.com/getsentry/sentry-android/releases

also, be aware that we are releasing our versions on `jcenter` and `bintray`, not on `mavenCentral` yet.

Does it help you? Thanks :)

**Comment by AndrewVovk** [comment]
With the latest alpha version (alpha08) Sentry classes are available.
Your answer helped a lot, thanks!

**Comment by headsvk** [comment]
hey @marandaneto now sentry-android 2.0.0 on bintray is broken

**Comment by marandaneto** [comment]
hey @headsvk please look at #270

**Comment by marandaneto** [comment]
@headsvk it's back on jcenter, please try it again :)
