### ISSUE TITLE
NDK Debug Source Libraries

### ISSUE THREAD

**Issue by colinrparker** [getsentry/sentry-android#188]
Thanks again for your work on the NDK support.

I am trying to figure out the best way to get library debug sources into the sentry ecosystem as part of my build.  I.e. so that I can get the stack trace from native crashes. I know that I can create a gradle task at the end of my build to call sentry-cli command directly with my .so files.

However, It appears that the sentry-android-gradle-plugin automatically uploads the java bundle.

Does the plugin have any options to upload the native libraries? Is that on the roadmap to update it to upload the libraries?

Thanks,

Colin

**Comment by marandaneto** [comment]
@colinrparker thanks for your question.

You are right, so far the sentry-android-gradle-plugin doesn't support the upload of the native libraries, but we are gonna work on it soon, actually, it is one of our priorities.

We will keep you posted :)

**Comment by marandaneto** [comment]
@colinrparker hey :) since version 1.7.30 it's already possible to upload debug source symbols, see https://github.com/getsentry/sentry-java/releases/tag/v1.7.30
there is a new version out supporting App bundles too btw, 1.7.31
Let us know if you find any issues.

**Comment by colinrparker** [comment]
@marandaneto Thanks!
