### ISSUE TITLE
Missing breadcrumbs in 2.0

### ISSUE THREAD

**Issue by headsvk** [getsentry/sentry-android#207]
_Platform:_
- [X]  Android -> min=21, compile/target=28, buildtools decided by AS
- [X]  Java -> 1.8
- [X]  Kotlin -> 1.3.61, target jvm 1.8
- [ ]  NDK -> If yes, which NDK/CMake version?

_IDE:_
- [X]  Android Studio -> 3.5.3
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [X]  Gradle -> 5.4.1
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [X]  Yes -> 3.5.3
- [ ]  No

_Sentry Android Gradle Plugin:_
- [X]  Yes -> 1.7.29
- [ ]  No

_Proguard/R8:_
- [X]  Enabled (tested in release)
- [X]  Disabled (tested in debug)

_sentry-android installed with:_
- [X] JCenter
- [ ] Bintray
- [ ] Manually

The version of sentry-android:
**2.0.0-beta02**

---
I have the following issue:
Breadcrumbs are not logged with events in 2.0 but they are logged in 1.7.29.

**Steps to reproduce:**
- Add breadcrumbs as shown here https://docs.sentry.io/platforms/android/#breadcrumbs
- Log a custom event using `Sentry.captureEvent(Event)` without adding breadcrumbs manually.

**Actual result:**
- Event is logged without the global breadcrumbs.

**Expected result:**
- Event is logged with the global breadcrumbs as in Sentry v1.

I debugged the source code of Hub.java and in the method `SentryId captureEvent(@NotNull SentryEvent event, @Nullable Object hint)`  on line 94, item.scope is quite empty, doesn't have any breadcrumbs and user I set, only a tag I set using `Sentry.setTag()`.

**Comment by marandaneto** [comment]
@headsvk hey, thanks for your question.

I've tried to reproduce this error, but it works on my side, see SS:

<img width="902" alt="Screenshot 2020-01-07 at 10 26 02" src="https://user-images.githubusercontent.com/5731772/71884306-56a7f980-3138-11ea-9f30-02817a0ac82e.png">

When you report a custom event using `Sentry.captureEvent(event)` and `event` has breadcrumbs, it won't report the global breadcrumbs, `event` has priorities over global ones, if you report a custom `event` without any breadcrumbs, it does report the global breadcrumbs.

Could you share a code snippet so I may try to reproduce it once more or even better, a repro repo?

Thanks :)

**Comment by headsvk** [comment]
@marandaneto I think I found the issues.
The api is not thread-safe anymore, in Sentry.java there's
```
private static final @NotNull ThreadLocal<IHub> currentHub = new ThreadLocal<>();
  
private static @NotNull IHub getCurrentHub() {
    IHub hub = currentHub.get();
    if (hub == null) {
      currentHub.set(mainHub.clone());
    }
    return currentHub.get();
  }
```
If I add a breadcrumb from a new thread, it will first clone the main scope and then add it to the new scope. Then if I log an event from another new thread, it will not see the scope with the breadcrumb.

**Comment by headsvk** [comment]
Okay it's simple, replace breadcrumb handling in MainActivity:
https://github.com/getsentry/sentry-android/blob/master/sentry-sample/src/main/java/io/sentry/sample/MainActivity.java#L40
```
    findViewById(R.id.breadcrumb)
        .setOnClickListener(
            view -> {
              new Thread(() ->
                Sentry.addBreadcrumb(new Breadcrumb("Thread " + Thread.currentThread().getId()))
              ).start();
            });
```

Click on add breadcrumb couple of times and then click capture exception. The exception is captured without any breadcrumbs.

Is it like this on purpose? If yes, it has to be documented that we should use the static Sentry methods from a single thread.

**Comment by marandaneto** [comment]
@headsvk ok, got it, thanks for raising this issue.

This is on purpose, the new SDK follows the unified API which is better described here (for concurrency) https://docs.sentry.io/development/sdk-dev/unified-api/#concurrency

We are discussing this issue internally as this makes a lot of sense for server-side, but not for Android.
We are gonna have a new proposal very soon.

Stay tuned.

**Comment by headsvk** [comment]
@marandaneto As a workaround I now use all static Sentry methods from a single thread, backed by `Executors.newSingleThreadExecutor()`, and it seems to work fine even for uncaught exceptions.

**Comment by marandaneto** [comment]
@headsvk nice, just be aware that if you are not on the crashed thread (the one that reported the error) might mess up the stack trace, because we use `Thread.currentThread().getStackTrace()` to map everything.
It might affect just a little or a lot, it depends on case by case.

**Comment by bruno-garcia** [comment]
Just an update. We realize in mobile having a shared scope by default makes a lot of sense and we'll be changing this soon

**Comment by marandaneto** [comment]
@headsvk hey, we took care of this issue (see #247) and it will land in the next release, stay tuned :)

**Comment by marandaneto** [comment]
hey @headsvk we've released a new version and you may try it out https://github.com/getsentry/sentry-android/releases/tag/2.0.0-rc02

you may remove your `ThreadExecutor` hack and call Sentry in any thread.

let us know if you still experience this problem :) thanks.
