### ISSUE TITLE
No default breadcrumbs recorded.

### ISSUE THREAD

**Issue by CarsonRedeye** [getsentry/sentry-android#210]
_Platform:_
- [x]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [x]  Kotlin -> If yes, which Kotlin (and jvmTarget) version? 1.3.50, targetCompatibility JavaVersion.VERSION_1_8
- [ ]  NDK -> If yes, which NDK/CMake version?

_IDE:_
- [x]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle -> If yes, which version? 4.10.1
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [x]  Yes -> If yes, which version? 3.3.2
- [ ]  No

_Sentry Android Gradle Plugin:_
- [x]  Yes -> If yes, which version? 1.7.28
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled

_sentry-android installed with:_
- [x] JCenter
- [ ] Bintray
- [ ] Manually

The version of sentry-android:
**2.0.0-beta02**

---
I have the following issue:

No breadcrumbs appear on sentry.io

**Steps to reproduce:**
1. add a line in app somewhere `throw Throwable("test")`
2. use emulator to throw error
3. Open sentry.io.

**Actual result:**
- No breadcrumbs shown on report

**Expected result:**
- Some breadcrumbs shown. The docs say "Sentry will automatically record specific events, to provide context to an error." What are these specific events, and are they supposed to show?

**Comment by marandaneto** [comment]
@CarsonRedeye hey, thanks for raising this issue.

We are gonna work on default integrations, so we are gonna be able to record breadcrumbs automatically, but not yet.
You can have some ideas on this blog post for now: https://blog.sentry.io/2019/12/10/new-android-sdk-how-to

Stay tuned.

**Comment by marandaneto** [comment]
@CarsonRedeye just a small update, I've removed that line from the docs, but I'll keep this issue open so track this feature request, thanks.

**Comment by marandaneto** [comment]
it'll be available on the next version, thanks.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-android/releases/tag/2.1.0-RC.1
