### ISSUE TITLE
There were 5 errors encountered while processing this event

### ISSUE THREAD

**Issue by nicolasjafelle** [getsentry/sentry-android#233]
_Platform:_
- Android -> Nexus 5x - SDK 23 / 6.0.1
- Kotlin -> 1.3.61

_IDE:_
- Android Studio -> 4.0 Canary 8

_Build system:_
- Gradle ->gradle-5.6.2-all

_Android Gradle Plugin:_
- Yes -> 3.5.3

_Sentry Android Gradle Plugin:_
- Yes -> 1.7.28

_Proguard/R8:_
- Enabled

_sentry-android installed with:_
- JCenter

The version of sentry-android:
**2.0.0-beta02**

---
I have the following issue:

I am seeing some messages saying "There were 5 errors encountered while processing this event". And below that this:
```
exception.values.0.stacktrace.frames: Discarded invalid value
Reason: expected a non-empty value

exception.values.1.stacktrace.frames: Discarded invalid value
Reason: expected a non-empty value

exception.values.2.stacktrace.frames: Discarded invalid value
Reason: expected a non-empty value

exception.values.3.stacktrace.frames: Discarded invalid value
Reason: expected a non-empty value
```
We are using Bitrise to generate this beta build and after we upload to Google Play Store Beta builds it started showing this 

Logcat is:
```
at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
    at java.lang.Thread.getStackTrace(Thread.java:580)
    at java.lang.Thread.getAllStackTraces(Thread.java:522)
    at io.sentry.core.SentryThreadFactory.getCurrentThreads(SentryThreadFactory.java:1)
    at io.sentry.core.MainEventProcessor.processNonCachedEvent(MainEventProcessor.java:6)
    at io.sentry.core.MainEventProcessor.process(MainEventProcessor.java:6)
    at io.sentry.core.SentryClient.captureEvent(SentryClient.java:15)
    at io.sentry.core.k.$default$captureException(ISentryClient.java:3)
    at io.sentry.core.SentryClient.captureException(SentryClient.java)
    at io.sentry.core.Hub.captureException(Hub.java:10)
    at io.sentry.core.i.$default$captureException(IHub.java:1)
    at io.sentry.core.Hub.captureException(Hub.java)
    at io.sentry.core.Sentry.captureException(Sentry.java:1)
    at e.e.f.b.a(SentryTree.kt:3)
    at m.a.a$b.a(Timber.java:14)
    at m.a.a$b.b(Timber.java:2)
    at m.a.a$a.b(Timber.java:6)
    at m.a.a.b(Timber.java:2)
```

**Comment by marandaneto** [comment]
@nicolasjafelle hey thanks for your message, I'll have a look at it.

**Comment by nicolasjafelle** [comment]
@marandaneto Hey! Thanks for the quick reply and fix. Quick question, that log is related to this fix? Mostly this part: `dalvik.system.VMStack.getThreadStackTrace(VMStack.java)`

**Comment by marandaneto** [comment]
@nicolasjafelle as I see, there were no errors on the event itself, but our protocol (backend) complains about empty frames, so I just don't set it if some threads don't actually have something.
So basically this fix only respects our protocol and won't show that warning on the dashboard.
I'm supposing that the event got sent and had no errors on it, am I right?

thanks.

**Comment by nicolasjafelle** [comment]
`I'm supposing that the event got sent and had no errors on it, am I right?` Yes, I think so. Seems to me Sentry for some reason shows something that maybe is something internally broken? And your PR fixed it.

**Comment by nicolasjafelle** [comment]
@marandaneto that means that the event in Sentry dashboards is something I need to pay attention from my side?

**Comment by marandaneto** [comment]
@nicolasjafelle I don't get your question, what do you mean?

**Comment by nicolasjafelle** [comment]
@marandaneto I mean is it a crash on my app and I need to prevent it? I never experience the same crash and log with Crashlytics, that is why I am confused.

**Comment by marandaneto** [comment]
@nicolasjafelle the warning on the dashboard is in our hand.
Your App. has called `Sentry.captureException`, this is in your hands if I got the question right.

**Comment by nicolasjafelle** [comment]
Aahh I realized I was implemented badly Timber with Sentry.

**Comment by marandaneto** [comment]
@nicolasjafelle hey, a new version has been published and you may be able to test it.

https://github.com/getsentry/sentry-android/releases/tag/2.0.0-rc01

Please, reopen the issue if you experience the same issue.

**Comment by nicolasjafelle** [comment]
Awesome! thanks for the news! Will try immediately
