### ISSUE TITLE
Duplication in API: BeforeSendCallback vs EventProcessor

### ISSUE THREAD

**Issue by angusholder** [getsentry/sentry-android#257]
I might be misunderstanding something, but it appears that SentryOptions.BeforeSendCallback and EventProcessor are identical in functionality: they both take the event and a hint object, can execute code before the send, can modify the event, and can even suppress the event.

Is there any more to it? It seems to me like you could remove the BeforeSendCallback type in favour of just using EventProcessors (as you can have multiple event processors set in the SentryOptions)

The body of SentryClient.executeBeforeSend is almost identical to that of the event processor code, except it handles exceptions, recording them as a breadcrumb

**Comment by marandaneto** [comment]
hey @angusholder there's some similarity, let's have a look at the docs
https://docs.sentry.io/guides/manage-event-stream/#outbound-filters

> beforeSend: A callback method invoked before an event is sent from your code runtime to Sentry with the event object passed to it as a parameter. Developers can hook into this callback to modify the event or drop it (filter) completely by returning null. You can filter outgoing events based on custom logic and data available on the SDK and event object like tags, environment, release version, error attributes, etc.

https://docs.sentry.io/development/sdk-dev/unified-api/#terminology

> event processors: Are callbacks that run for every event. They can either return a “new” event which in most cases means just adding data OR return null in case the event will be dropped and not sent.

I'd agree with you, but there are two main differences:

 * beforeSend is always final, where event processors depend on the order
* event processors are much easier to share, as you can eg. create one as a 3rd party package in your organization and then just import it and register in all the projects, while still maintaining your own beforeSend.

I hope that clears it up, if so, please close the issue, thanks :)
