### ISSUE TITLE
sentry-android not available through jcenter

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-android#270]
I've requested a merging on jcenter of our 2 repos, `sentry-java` (io.sentry:sentry-android) current version 1.7.x and the new repo `sentry-android` (also io.sentry:sentry-android) current 2.0.0.

as a workaround, please use `bintray` till this process gets done.
https://dl.bintray.com/getsentry/sentry-android

eg
https://dl.bintray.com/getsentry/sentry-android/io/sentry/sentry-android/2.0.0/

if you still wanna use `jcenter`, it's possible using the `io.sentry:sentry-android-ndk` module, it'll have the same dependencies as `sentry-android` or if you don't wanna support NDK, just `io.sentry:sentry-android-core`.

thanks for understanding.

**Comment by SaezChristopher** [comment]
I confirm. Maybe the team remove it intentionally ?

**Comment by marandaneto** [comment]
@SaezChristopher it was intentional because it's part of the merging process made by jcenter, I've sent them an email to see how to fix it and/or how long it takes, last case, I'll deploy it again as soon as I get an answer.

this was done because when people were searching for `io.sentry` on jcenter, they were finding 2 `sentry-android` artifacts and the newest one (2.0.0) was at the 2nd page, and most people don't even go next page, we decided to merge it so one could see all versions in one package from 1.x to 2.0.0.

**Comment by SaezChristopher** [comment]
Alright, i didn't get it but now its vsound ery clear. Thx for full explanation :)

**Comment by marandaneto** [comment]
sure, stay tuned :)

here is the link of what is being done https://www.jfrog.com/confluence/display/BT/Managing+Uploading+Content+New+UI#ManagingUploadingContentNewUI-MergingPackages

thanks for understanding.

**Comment by marandaneto** [comment]
code snippet to add bintray repo:

```
    repositories {
        maven {
            url = "https://dl.bintray.com/getsentry/sentry-android"
        }
    }
```

**Comment by DevelopSmith** [comment]
@marandaneto Thanks a lot for the great help. Keep the great work up!

**Comment by AdamGerthel** [comment]
@marandaneto where exactly do I add the snippet? Sorry for the confusion, but I'm very unfamiliar with Android builds & gradle. I have two build.gradle files in my RN app, none of which seem suitable for that line..? Or at least I'm very unsure of where exactly to enter it.

**Comment by marandaneto** [comment]
@AdamGerthel it could be in both, but let's say the one in the root folder of the android app.

you will see something like:

```
allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        // HERE:
        maven { url = "https://dl.bintray.com/getsentry/sentry-android" }
    }
}
```

look for the `// HERE:` comment, that should help.

**Comment by AdamGerthel** [comment]
@marandaneto thanks!

**Comment by marandaneto** [comment]
just a small update, bintray/jcenter is investigating why the sync isn't happening, they will let us know asap.

**Comment by ovbm** [comment]
Workarounds didn't work in my case, still got: 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets_SentryUpload'.
> Process 'command 'node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1
```

**Comment by marandaneto** [comment]
hey people, the issue should be resolved and no workarounds are needed anymore, please try it again.

I can see the artifacts in https://jcenter.bintray.com/io/sentry/sentry-android/ already.

Please let us know if you find any issues, thanks for the patience.

**Comment by ovbm** [comment]
Can't confirm that the issue is fixed.

**Comment by marandaneto** [comment]
@ovbm I think you are having a different issue, this one is related to `sentry-android` being available on jcenter.
Kindly refer to https://github.com/getsentry/sentry-react-native/issues
It might be related to `sentry-cli`, thanks.

**Comment by ovbm** [comment]
ah ok, sorry for the confusion. This issue is mentioned in https://github.com/getsentry/sentry-react-native/issues/767 as a workaround, so I thought they might be the same.
