### ISSUE TITLE
ObsoleteLintCustomCheck warning since 2.0.0

### ISSUE THREAD

**Issue by soucolline** [getsentry/sentry-android#274]
Hello,

We’re having a warning triggered when trying to update to the 2.0.0 version : 

```
/root/.gradle/caches/transforms-2/files-2.1/ee27474a39507de9d1cb5ad8961ab879/annotation-experimental-1.0.0/jars/lint.jar#L0 - Lint found an issue registry (androidx.annotation.experimental.lint.ExperimentalIssueRegistry) which did not specify the Lint API version it was compiled with.
This means that the lint checks are likely not compatible.

If you are the author of this lint check, make your lint IssueRegistry class contain
  override val api: Int = com.android.tools.lint.detector.api.CURRENT_API
or from Java,
  @override public int getApi() { return com.android.tools.lint.detector.api.ApiKt.CURRENT_API; }

If you are just using lint checks from a third party library you have no control over, you can disable these lint checks (if they misbehave) like this:

    android {
        lintOptions {
            disable “UnsafeExperimentalUsageError”,
                    ”UnsafeExperimentalUsageWarning”
        }
    }
```

Does it seem something that could be linked to the update ?

Cheers

**Comment by marandaneto** [comment]
@soucolline hey, to be honest, I don't think so, we don't use `androidx.annotation`,

Which AGP version are you using with? it might be related to it, so I could give it a try or of course, a sample repo to reproduce the issue would be also very helpful, thanks.

**Comment by soucolline** [comment]
@marandaneto thanks for the answer, we are using version 3.5.3
`classpath 'com.android.tools.build:gradle:3.5.3'`

**Comment by marandaneto** [comment]
@soucolline I see, well, we use this version too, pretty sure it's not `sentry-android` raising it.
we only use `gson` as a dependency and nothing more.

Try to:
`./gradlew :your-app:dependencies` and you might find out the guilty one, good luck :)
