### ISSUE TITLE
Is the ACCESS_NETWORK_STATE permission required?

### ISSUE THREAD

**Issue by lateplate** [getsentry/sentry-android#295]
Hi,

I believe at one point in the 1.x days the ACCESS_NETWORK_STATE permission was required (or strongly suggested). Is this still the case for 2.x?

I can't seem to find any documentation confirming one way or the other if it's absolutely required. We are trying to pare down our use of permissions as much as possible so wanted to validate this one.

[The source](https://github.com/getsentry/sentry-android/blob/27bb71a53d6db4b7822b36a9e815263a160535bf/sentry-core/src/main/java/io/sentry/core/transport/AsyncConnection.java#L166) seems to imply that if the network state can't be determined or isn't available, that a retry will be set?

Thanks!

**Comment by marandaneto** [comment]
Hey @lateplate, thanks for your message.

`ACCESS_NETWORK_STATE` is not fully required, but it is recommended though.

if you look at https://github.com/getsentry/sentry-android/blob/master/sentry-android-core/src/main/java/io/sentry/android/core/util/ConnectivityChecker.java
and https://github.com/getsentry/sentry-android/blob/master/sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransportGate.java you'll see that we test the `ACCESS_NETWORK_STATE` permission and if it's not available, we'll assume that the device is `online` as a fallback.

we don't add `ACCESS_NETWORK_STATE` automatically, so it's up to the client to whether use it or not.
`android.permission.INTERNET` is merged automatically.

I hope that clears up your question :)

**Comment by lateplate** [comment]
Aha, thank you! I missed the condition where it defaults `isConnected` to true.

Can I assume if it believes it's online, but is actually offline, the upload to Sentry will be silent failure / a checked exception? That is, nothing will bubble up to the app as an error, so there wouldn't be any disruption to the user?

Also, if the app was offline, it does attempt to retry on next start?

Thanks again for the quick response!

**Comment by marandaneto** [comment]
hey @lateplate yes and yes, glad to help :)
