### ISSUE TITLE
Feature request: logging transport

### ISSUE THREAD

**Issue by mike-burns** [getsentry/sentry-android#296]
The Ruby library offers [a `stdout` transport](https://github.com/getsentry/raven-ruby/blob/8c1e62ba5b8797ea7c16b36bfb7bd1f7af8c6132/lib/raven/transports/stdout.rb) in addition to `https`. We've been using that while in development because it effectively treats exceptions as log output.

Regardless, it'd be great to have similar functionality in Android: a transport that logs instead of sending it to the server. My understanding is that it could be integrated like so:

```kotlin
SentryAndroid.init(applicationContext) { options ->
    if (BuildConfig.DEBGUG)
        options.transport = LoggingTransport()
}
```

---

I tried to implement one locally for just my app but `TransportResult` is not public.

**Comment by marandaneto** [comment]
hey @mike-burns thanks for your message.
yep, that sounds a nice use case, I'll check internally and get back to you.

**Comment by marandaneto** [comment]
@mike-burns just a quick inspiration for you https://github.com/getsentry/sentry-android/pull/298
while I don't have much time over the next week, PRs are welcome, I'd gladly do a code review, thanks.

**Comment by mike-burns** [comment]
That was fast!

I also cannot promise time over the next week but I'd like to see if I can add tests to that implementation and get it ready to be merged. High chance you'll beat me to that, though, since you know the codebase much better.

**Comment by marandaneto** [comment]
ahh I've missed your message about the `TransportResult`, it will be public in the next version #300 :)
you could create a `io.sentry.core.transport` package and hack the access modifier as I did in my sample for now, sorry about that.

**Comment by marandaneto** [comment]
@mike-burns merged, thanks for your contribution :)
It'll be available in the next release.
