### ISSUE TITLE
SentryEvent getThrowable

### ISSUE THREAD

**Issue by farfromrefug** [getsentry/sentry-android#334]
In the current sentry-android code it is impossible to access an event throwable.
https://github.com/getsentry/sentry-android/blob/f53d6b4323920825e1aac4e885415b8f2491bdad/sentry-core/src/main/java/io/sentry/core/SentryEvent.java#L67
However in my case i would need to do so:

I use sentry-android within Nativescript cross-platform framework. when the UncaughtExceptionHandlerIntegration catch an error i get to know it through the BeforeSendCallback. This is where i would like to access the throwable because it actually contains the JS stack that i would need to parse and add to the event before sending it.

Could you make the `getThrowable` method public?

Thanks

**Comment by marandaneto** [comment]
hey @farfromrefug thanks for your message.

ideally, all the important information from `throwable` should be available through the field `exception`.
would you mind sharing a snippet or even opening a PR of how you'd parse that? have a look at `SentryExceptionFactory` and `SentryStackTraceFactory`.
It might be useful for others, so we could bring it in by default, thanks.

**Comment by farfromrefug** [comment]
@marandaneto that s where it gets tricky :D 
I mean i do all that from Nativescript, which means javascript :D 
Anyway i got it working using reflection which i dont want
https://github.com/farfromrefug/nativescript-akylas-sentry/blob/master/src/nssentry.android.ts#L378

So to explain:
* when a Java errors occurs when called from a JS method(in N) then Nativescript throws a [NativescriptException](https://github.com/NativeScript/android-runtime/blob/f3657adf30e58bcde653a63c5f6a31a297d44d1c/test-app/runtime/src/main/java/com/tns/NativeScriptException.java)
* that exception as an [incomingStackTrace](https://github.com/NativeScript/android-runtime/blob/f3657adf30e58bcde653a63c5f6a31a297d44d1c/test-app/runtime/src/main/java/com/tns/NativeScriptException.java#L36) which is a string version of the JS stack
* i get that stacktrace then i parse it kind of the normal way
* However i have to use a few tricks because that exception does not go through all the sentry integrations (like rewrite frames).

I have to look at `SentryExceptionFactory` and `SentryStackTraceFactory`, Do you think i could handle it there instead?

**Comment by marandaneto** [comment]
@farfromrefug thanks for the detailed message :)

I see your point, we do something similar to `react-native`, see https://github.com/getsentry/sentry-react-native/blob/master/android/src/main/java/io/sentry/RNSentryModule.java#L87

as `sentry-react-native` bundles `sentry-javascript`, the exception is already sent by the JS layer and we just dispose it on the Android side, but unfortunately, we don't support NativeScript yet.

**Comment by marandaneto** [comment]
I'll keep this open as a feature request and figure it out on how this should be done, as you made it to work using reflection, adding it directly to `SentryExceptionFactory` won't be a good idea as it's an implementation detail of hybrid apps.

**Comment by marandaneto** [comment]
this has been made public but still an internal API.
you won't need to use reflection but still on your own risk.

https://github.com/getsentry/sentry-android/blob/feat/sentry-java/sentry-core/src/main/java/io/sentry/core/SentryEvent.java#L69-L73

soon to be merged and released, so I'll close this issue, thanks.
