### ISSUE TITLE
What Permission is required for proguard upload?

### ISSUE THREAD

**Issue by vincent-paing** [getsentry/sentry-android#335]
We're currently adding Internal Integration instead of user-specific auth token. Since there's different permission levels, can you clarify which access is specifically required for proguard upload?

**Comment by marandaneto** [comment]
hey @vincent-paing thanks for your message.

you should create an `API Token` and use `project:releases` as a Scope.
https://sentry.io/settings/account/api/auth-tokens/

Does that help?

**Comment by vincent-paing** [comment]
> hey @vincent-paing thanks for your message.
> 
> you should create an `API Token` and use `project:releases` as a Scope.
> https://sentry.io/settings/account/api/auth-tokens/
> 
> Does that help?

So I can't use Internal Integration(which is the recommended way) and have to use my personal account's auth token?

**Comment by vincent-paing** [comment]
Update: I managed to make it work with personal auth token. But now I'm getting ``413 Request Entity Too Large``.

**Comment by marandaneto** [comment]
@vincent-pain oh I see, let me double-check with my team and I let you know asap.

**Comment by vincent-paing** [comment]
> @vincent-paing oh I see, let me double-check with my team and I let you know asap.

I just gave all permissions to my internal integration setup and it seems to work but I can't seem to figure out which one is explicitly needed. I will play around with different settings when I get a chance too

**Comment by marandaneto** [comment]
@vincent-paing have you tried only this one?

![image (1)](https://user-images.githubusercontent.com/5731772/78346178-f5f55500-759e-11ea-8c02-209f30d0ca6a.png)

**Comment by marandaneto** [comment]
Closing the issue, as it seems like the original issue has been resolved.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
