### ISSUE TITLE
Need to know the module of Exception

### ISSUE THREAD

**Issue by himgupta229** [getsentry/sentry-android#351]
Hi
My use case is that I am developing a library module and to track its crashes I am using sentry-core 2.0.0.I would like to filter out the crashes of my module only so that I can debug them and exclude any other crashes including those of caller application's also.I used beforesend callback but in the event I am unable to find module on which exception is happening so can't apply filter to check whether the exception occurred in our module or someone else's.How can I achieve it?

**Comment by marandaneto** [comment]
hey @himgupta229 thanks for your question.

```
       options.setBeforeSend((event, __) -> {
         if (event.getExceptions() != null && !event.getExceptions().isEmpty() && event.getExceptions().get(0).getModule().equals("your.package")) {
           
           // you can even look up at the the frames or just return the event at this point
           for(SentryStackFrame item : event.getExceptions().get(0).getStacktrace().getFrames()) {
              if (item.getModule().equals("your.package")) {
                return event; // send the event
              }
           }
         }
         return null; // drop the event
       });
```

The `SentryException` and `SentryStackFrame` have a field called `module`, you may use them.
Does that help? thanks.

**Comment by himgupta229** [comment]
Can an application have more than one Sentry initializations? I mean as I already told that I would be using Sentry as part of my library module which will be included in our client's android application, so if the client's application also uses Sentry will it cause trouble?

**Comment by marandaneto** [comment]
@himgupta229 please close this issue if my answer above solves your request.

About being a library, there are a few problems with it, but it's possible if the side effects are not a big deal for you.
eg App minifies your library too (so your stack traces will be minified).
You should also not use `Sentry` static class or it'll be overwritten by Sentry on the final App.
I'd recommend you to create your own `Hub/SentryClient` but don't forget to manually set all the required options to `SentryOptions`.

We intend to support libraries natively with no extra code required, but we are not there yet.

A bit more of context https://github.com/getsentry/sentry-android-gradle-plugin/issues/3

**Comment by marandaneto** [comment]
Closing the issue, as it seems like the original issue has been resolved.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
