### ISSUE TITLE
Exception cause is reported instead of actual exception since SDK 2.0.0

### ISSUE THREAD

**Issue by mrmitew** [getsentry/sentry-android#363]
_Platform:_
- [x]  Android -> 
build tools: 29.0.2
compileSdk: 28
- [x]  Kotlin -> Unrelated to the issue

_IDE:_
- [x]  Android Studio -> Unrelated to the issue

_Build system:_
- [x]  Gradle -> Unrelated to the issue

_Android Gradle Plugin:_
- [x]  Yes -> Unrelated to the issue

_Sentry Android Gradle Plugin:_
- [x]  No

_Proguard/R8:_
- [x]  Enabled

_sentry-android installed with:_
- [x] JCenter

The version of sentry-android:
**2.0.0**

---
I have the following issue:

After upgrading Sentry's SDK version to 2.0.0, exception cause is displayed on the dashboard and not the actual exception. Developer has to click on an event, then scroll all the way down to the last breadcrumb to see the actual exception.

**Steps to reproduce:**
- Step 1 Report `IllegalStateException(MyCustomException("Some message"))`

**Actual result:**
On the dashboard you'll see it is reported as:
**MyCustomException**
Some message

When you tap on it to see details, scroll down to the last breadcrumb, you'll see: **IllegalStateException:** MyCustomException: Some message

**Expected result:**
- On the dashboard:

**IllegalStateException**
MyCustomException: Some message

- And in the details:

**IllegalStateException:** MyCustomException: Some message

**Comment by marandaneto** [comment]
@mrmitew hey thanks for your message.

Sorry but I don't follow the problem here.

Why do you mention `breadcrumbs` here? if you clearly is calling only `captureException` and not `addBreadcrumb`?

<img width="897" alt="Screenshot 2020-04-17 at 08 36 45" src="https://user-images.githubusercontent.com/5731772/79539688-1a652d00-8087-11ea-8bc2-306e7cc877ef.png">

Looks good to me, the exception and the cause.

<img width="676" alt="Screenshot 2020-04-17 at 08 39 54" src="https://user-images.githubusercontent.com/5731772/79539748-39fc5580-8087-11ea-8e91-859318aa6f39.png">

Do you mean that here we should also mention `IllegalStateException`?

**Comment by mrmitew** [comment]
Hey @marandaneto :)

Yes, that's what I meant indeed. The actual exception is not visible in the issue list (the overview with all issues).

I meantioned breacrumbs, because that's where developer can see the actual exception, not the cause.

Here `BaseException` was wrapped into an `IllegalStateException`.
<img width="1664" alt="Screen Shot 2020-04-17 at 4 59 10 PM" src="https://user-images.githubusercontent.com/8547755/79583107-f9272f80-80cc-11ea-8307-589252c47c28.png">

But on the dashboard we can only see the cause - `BaseException`, which of course is still useful, but not when developers are expecting to see the exception they are logging (in this case `IllegalStateException`)

**Comment by marandaneto** [comment]
> Hey @marandaneto :)
> 
> Yes, that's what I meant indeed. The actual exception is not visible in the issue list (the overview with all issues).

ok, got it, I don't think this has changed from the old version, I'll dig into it.

> I mentioned breacrumbs, because that's where Sentry displays the actual exception, not the cause.
> 
> Here `BaseException` was wrapped into an `IllegalStateException`.
> <img alt="Screen Shot 2020-04-17 at 4 59 10 PM" width="1664" src="https://user-images.githubusercontent.com/8547755/79583107-f9272f80-80cc-11ea-8307-589252c47c28.png">

We don't add breadcrumbs automatically, isn't you adding those?

> But on the dashboard we can only see the cause - `BaseException`, which of course is still useful, but not when developers are expecting to see the exception they are logging (in this case `IllegalStateException`)

I'll double-check it with my team, stay tuned.

**Comment by marandaneto** [comment]
hey @mrmitew you were right, good catch.
there's a fix already and it'll be available on the next version, thanks.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-android/releases/tag/2.1.0-RC.1
