### ISSUE TITLE
ANR while uploading crashes.

### ISSUE THREAD

**Issue by himgupta229** [getsentry/sentry-android#380]
_Platform:_
- [x]  Android -> compilesdk - 29,targetsdk - 29,buildtools - 29.0.3
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?

_IDE:_
- [x]  Android Studio ->3.5.3
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle -> 5.4.1
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [x]  Yes ->3.5.3
- [ ]  No

_Sentry Android Gradle Plugin:_
- [x]  No

_Proguard/R8:_
- [x]  Disabled

_sentry-android installed with:_
- [x] JCenter

The version of sentry-android:
**2.0.3**

---
I have the following issue:

I am trying to integrate Sentry in my library module so the thing goes like that the host application has also integrated Sentry(with different DSN than mine).In my library module I have created an instance of Thread.UncaughtExceptionHandler and on **uncaughtException** I am calling the below code
`sentryClient.captureEvent(SentryEvent(e))` 
where client is SentryClient object initialized as below.
`var sentryOptions = SentryAndroidOptions();
        sentryOptions?.setBeforeSend { <Override this callback for custom handling>}
        sentryOptions?.dsn = <my dsn>
        val cacheDir = File(context.getCacheDir(), "CustomSentry")
        cacheDir.mkdirs()
        sentryOptions.cacheDirPath = cacheDir.absolutePath
        val sentryClient = SentryClient(sentryOptions, null)
         `
where as in case of host application it is integrated by keeping dsn in application's manifest.
**Steps to reproduce:**
- As soon the application gets launched I am throwing an exception. Hence my custom crash logger gets called and the application gets freezed.

**Actual result:**
The application
[anr_2020-04-29-14-25-31-785.log](https://github.com/getsentry/sentry-android/files/4551151/anr_2020-04-29-14-25-31-785.log)

 gets freezed.ANR occurs

**Expected result:**
- ANR shouldn't occur.

**Comment by himgupta229** [comment]
https://gist.github.com/himgupta229/83b4fd61f294020258976e3edb10b16a

**Comment by marandaneto** [comment]
@himgupta229  thanks for your message.

We don't support Android libs by default, but it's possible if you create your own SentryClient.
Context: https://github.com/getsentry/sentry-android-gradle-plugin/issues/3

Can you create a test project that I can reproduce this easily? It'd be very helpful :) thanks.

**Comment by himgupta229** [comment]
> @himgupta229 thanks for your message.
> 
> We don't support Android libs by default, but it's possible if you create your own SentryClient.
> Context: [getsentry/sentry-android-gradle-plugin#3](https://github.com/getsentry/sentry-android-gradle-plugin/issues/3)
> 
> Can you create a test project that I can reproduce this easily? It'd be very helpful :) thanks.
Hi,
I have created a test project [here.](https://github.com/himgupta229/customapp)

**Comment by marandaneto** [comment]
thanks @himgupta229

**Comment by marandaneto** [comment]
@himgupta229 one of your modules is not source/target Java 8.
Also, I'd make both of the modules as Kotlin jvmTarget Java 8.

To be able to send an event using a custom SentryClient, your custom SentryOptions also needs to have a `Serializer` and our class `AndroidSerializer` is not public.

We'll need to improve that, as I said, we are not fully supporting libs yet.

This class is package-private, so pretty sure you know how to hack it :)

**Comment by marandaneto** [comment]
if you want Sentry to be fully compatible with libs, please raise a new issue for that, so we can tag as an enhancement, thanks.
