### ISSUE TITLE
Support Sentry in Library modules ootb

### ISSUE THREAD

**Issue by himgupta229** [getsentry/sentry-android#393]
Hi,
As discussed in issue[(https://github.com/getsentry/sentry-android/issues/380)] I have done the changes to initialise AndroidSerializer but it happens sometimes crash is not logged by library module sentry object but it gets cached by the application sentry object.Seems like library module's sentry is caching the exception and I don't know the way how to upload that cached crash to the server.Can you guys help.Github project link - https://github.com/himgupta229/customapp

**Comment by marandaneto** [comment]
hey, you'd need to set all the required options, most of them are set on `SentryAndroid.init` which is not used by your lib as you create its own `SentryClient`.
So be sure that your custom `SentryOptions` have all the necessary things.

https://github.com/getsentry/sentry-android/blob/master/sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java

**Comment by marandaneto** [comment]
@himgupta229 btw PRs are welcome, if you make the necessary changes in the SDK in order to support libs (without extra code), we'd love to bring this in, thanks.

**Comment by himgupta229** [comment]
Hi,
I have added the initialization of SentryAndroidoptions object fields in the CrashManager class but still unable to log crash. What I suspect that it is not able to upload crashes that are cached in my custom cache directory but it is uploading the crashes that are present in the Application's cache directory. Am I missing something?

**Comment by marandaneto** [comment]
have you looked at the necessary `addIntegration` calls?

**Comment by himgupta229** [comment]
As I am creating an instance of AndroidSentryOptions integrations are being added by default.But I think that they are not getting called as I am using SentryClient to capture crashes not the way Sentry.init works.Hence even though SendCachedEventFireAndForgetIntegration is being added but it is not getting executed.

**Comment by himgupta229** [comment]
Do I have to iterate through my custom cache directory read through every event deserialize it and then again call SentryClient.capture(sentryEvent)?

**Comment by marandaneto** [comment]
> As I am creating an instance of AndroidSentryOptions integrations are being added by default.But I think that they are not getting called as I am using SentryClient to capture crashes not the way Sentry.init works.Hence even though SendCachedEventFireAndForgetIntegration is being added but it is not getting executed.

try creating a `Hub` instead of a `SentryClient` directly, it might be better, the `Hub` does the necessary job for making integrations to be registered.
or you do the registering by yourself, which requires a hub anyway
https://github.com/getsentry/sentry-android/blob/master/sentry-core/src/main/java/io/sentry/core/Hub.java#L37

you need to track the `SentryAndroid.init` down and do the necessary things to make `SentryClient` to work properly, fork this repo and run the sample, it's gonna help you to understand the workflow and necessary changes.

This is not our high priority right now and I can't really spend much time on it.

**Comment by himgupta229** [comment]
is there any documentation available to create an event via api?

**Comment by marandaneto** [comment]
@himgupta229 https://develop.sentry.dev/sdk/overview/
our docs are pretty rich.
