### ISSUE TITLE
Unlabeled event reported from SDK, visible after each release

### ISSUE THREAD

**Issue by tajchert** [getsentry/sentry-android#400]
_Platform:_
- [x]  Android -> 6.0.1
- [x]  Java -> 1.8
- [ ]  Kotlin ->
- [ ]  NDK -> If yes, which NDK/CMake version?

_IDE:_
- [x]  Android Studio -> stable 3.6.1
- [ ]  IntelliJ ->
- [ ]  Other ->

_Build system:_
- [x]  Gradle -> 5.6.4
- [ ]  Buck -> 
- [ ]  Bazel ->
- [ ]  Other ->

_Android Gradle Plugin:_
- [x]  Yes -> 3.6.3
- [ ]  No

_Sentry Android Gradle Plugin:_
- [x]  Yes -> 1.7.31
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled

_sentry-android installed with:_
- [x] JCenter
- [ ] Bintray
- [ ] Manually

The version of sentry-android:
**2.1.0**

---
I have the following issue:

I'm seeing "<unlabeled event>" without any stacktrace (just breadcrumbs with TYPE_AMBIENT_TEMPERATURE). This happens regularly after each release.

**Steps to reproduce:**
- Release app to Google Play, submit to review. When app goes through automatic review process.

**Actual result:**
- Each time "<unlabeled event>" is reported to Sentry. Level = error. Always from Android 6.0.1.

**Expected result:**
- No such event should be reported, or there should be more data (ex. stacktrace).

Below whole preview of this event.
![screencapture-sentry-io-organizations-kanarek-issues-1654355210-2020-05-09-13_21_10](https://user-images.githubusercontent.com/2962633/81472379-0761fa80-91f8-11ea-9081-8bf4f9754d8e.png)

**Comment by marandaneto** [comment]
hey @tajchert thanks for raising this.

you can disable the automatic system events (breadcrumbs) if you wish:

https://github.com/getsentry/sentry-android/blob/master/sentry-sample/src/main/AndroidManifest.xml#L79-L80

what do you mean by `Each time "" is reported to Sentry. Level = error.` I don't get it.

Are you doing `Sentry.captureMessage("")`?

**Comment by tajchert** [comment]
I mean that every time I upload the app to Google Play I get such event inside Sentry dashboard. It seems to be reported during automatic testing by Google Play as I'm not seeing those events on production later on.

> Are you doing Sentry.captureMessage("")?
No, I'm not doing anywhere in my code a capture of empty (or null) Message. I just rechecked that.

About stacktrace for message - I will enable it in next build to pin point place from where that one is coming from.
About turning off system breadcrumbs - nice tip, not related to this issue exactly but valuable.

**Comment by tajchert** [comment]
I enabled logging stack traces and turned off system-events breadcrumbs. 
Released new version to Google Play - no "<unlabeled event>" was registered inside Sentry.
I made no other changes compared to build that resulted in logging such event.

In such case I don't see how we can debug it and would suggest closing it. I will comment back if I ever have such event registered (without calling inside my code Sentry.captureMessage("")).

**Comment by marandaneto** [comment]
@tajchert thanks for this.

I have no idea how to repro this.
I believe you call `Sentry.captureMessage(var)` at some point and Google ran tests on it and that variable was empty, just a guess though.

Let's close it and watch it, thanks!

**Comment by tajchert** [comment]
Sadly it appeared yet again. Without system-events, but still no stack trace (it was correctly added to my other Message event).

![screencapture-sentry-io-organizations-kanarek-issues-1654355210-2020-05-10-18_17_31](https://user-images.githubusercontent.com/2962633/81504615-90595e80-92ea-11ea-92cc-3dd90f8e06b7.png)

I would wait for somebody else to confirm same behaviour, also for me it is not a big issue as it happens once after each app release (hey, it might be a feature to confirm that on production version Sentry is running - just joking ;) ).

**Comment by marandaneto** [comment]
@tajchert thanks for reporting again.
yeah, that's odd and intriguing, but I don't think it's an SDK bug at all.
Let's see if we get more reports, thanks.
