### ISSUE TITLE
Cannot manually init Sentry in Application.attachBaseContext

### ISSUE THREAD

**Issue by ninniuz** [getsentry/sentry-android#408]
_Platform:_
- [x]  Android -> API 28
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?

_IDE:_
- [x]  Android Studio -> 3.6.3
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle -> 5.6.4
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [x]  Yes -> 3.6.3
- [ ]  No

_Sentry Android Gradle Plugin:_
- [x]  Yes -> 1.7.23
- [ ]  No

_Proguard/R8:_
- [x]  Enabled
- [ ]  Disabled

_sentry-android installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of sentry-android:
**2.1.0**

---
I have the following issue:

If I manually init Sentry with `SentryAndroid.init(context)` from inside `Application#attachBaseContext` I will get an exception.

Root cause: https://github.com/getsentry/sentry-android/blob/46658948a80bebade5ebe07402e38ec6384f1669/sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java#L51

`getApplicationContext` will return `null` when called from `attachBaseContext`

**Comment by marandaneto** [comment]
hey @ninniuz thanks for raising this.

true, guess I can fix this with:

```
    if (!(context instanceof Application) && context.getApplicationContext() == null) {
      throw new IllegalArgumentException("The application context is required.");
    }
```

Tomorrow I'll check this out.

just out of curiosity, any particular reason to use `attachBaseContext` instead of `onCreate`?

**Comment by ninniuz** [comment]
We have some logic for custom language configuration and we have to do that in that method. Since it might fail, we need to be able to have Sentry up and running by then.
If I'm not wrong, we already discussed this in the old SDK as well so you might have some reference there.
Thanks!

**Comment by marandaneto** [comment]
hey, I will look this up tomorrow then, thanks @ninniuz

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-android/releases/tag/2.1.2
