### ISSUE TITLE
Android stack trace and errors are not displayed

### ISSUE THREAD

**Issue by Mohamed-Abbas** [getsentry/sentry-android#426]
_Platform:_
- [X]  Android -> Device API=8.0.0  compileSdkVersion=28  targetSdkVersion=28  Buildtools=28.0.3
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [X]  React-Native -> 0.61.5

_IDE:_
- [ ]  Android Studio 
- [ ]  IntelliJ -> If yes, which version?
- [X]  Other -> vscode

_Build system:_
- [X]  Gradle -> 5.5
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [X]  No I'm not sure on this one

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No. 
Again I'm not sure on this one, I'm using the react-native plugin but since the error is only on Android I'm reporting her

_Proguard/R8:_
- [ ]  Enabled
- [X]  Disabled

_sentry-android installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of sentry-android:
**2.x.x**

The version of @sentry/react-native: 1.3.9

---
I have the following issue:

Android stack trace  and errors are not showing up on release and debug builds, i can confirm that source maps files are uploaded, release and distributions matches correctly. For IOS it is working as expected.

<img width="840" alt="Screen Shot 2020-05-19 at 12 25 07 PM" src="https://user-images.githubusercontent.com/26598024/82443637-1d967300-9aa2-11ea-86d1-473c736583d5.png">

**Steps to reproduce:**
Add the following code
setTimeout(() => { throw new Error('first error'); }, 30000);

**Actual result:**
stack trace shows Thread Errored

**Expected result:**
stack trace should be available along with source code responsible for the error

**Comment by marandaneto** [comment]
duplicated of getsentry/sentry-react-native/issues/853
it's fine to create the issue here, but please create just in one of them, either here or `getsentry/sentry-react-native`

**Comment by dabo248** [comment]
Still having this issue on sentry-android and not sure how the react-native fix could help me. Any ideas?

**Comment by marandaneto** [comment]
@dabo248 do you have a native Android App or a React native App?

If a native Android App, are you doing a `Sentry.captureMessage(...)`? they don't include stack traces by default, but if you wish to, you can toggle the feature on `SentryOptions.attachStackTraces`.

If you do `Sentry.captureException(...)`, you should see stack traces by default, if not, please raise a new issue, thanks.

**Comment by dabo248** [comment]
@marandaneto I have native Android App written in Kotlin. I use `io.sentry:sentry-android:2.3.0` in it.

I capture most of my stuff with `Sentry.captureEvent(...)`. Neither `isAttachStacktrace` nor `isAttachThreads` did help in showing up stack traces. I only see the red "Thread Errored" hint. This is my init function:

```
fun init(context: Context) {
        SentryAndroid.init(
            context
        ) { options: SentryAndroidOptions ->
            options.isAttachStacktrace = true
            options.isAttachThreads = true
        }
    }
```

**Comment by marandaneto** [comment]
@dabo248 if you use `Sentry.captureEvent(...)` that takes a `SentryEvent`
when creating a new instance of `SentryEvent`, you need to pass an exception (Throwable) to the ctor.
so `Sentry.captureEvent(SentryEvent(RuntimeException()))` would work ootb, what it was missing is, the exception itself.

**Comment by dabo248** [comment]
I also actually also use `Sentry.captureMessage(...)` at a couple of places and I would also like to send the stack trace there. It doesn't get sent, even when I turn `isAttachStacktrace` on.
