### ISSUE TITLE
Health metrics not being shown in onpremisse server (FileNotFoundException on /api/2/envelope)

### ISSUE THREAD

**Issue by carlosrivin** [getsentry/sentry-android#453]
_Platform:_
- [x]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
Android 10,  28 / 28
- [x]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
Most of the app is in Java 1.8
- [x]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
jvmTarget = 1.8
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?

_IDE:_
- [x]  Android Studio -> If yes, which version?
4.0 Stable channel
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle -> If yes, which version?
gradle-6.4.1
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
4.0.0
- [ ]  No

_Sentry Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
'io.sentry:sentry-android-gradle-plugin:1.7.34'
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled
Happens also on debug (no proguard) builds

_sentry-android installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of sentry-android:
**2.1.6**

---
I have the following issue:
The release tab on my onpremisse sentry doesn't show up any health metric. I have the setup as described in the docs but I see no "crash free users" or any other metrics like that.
I have the onpremisse server updated to the most recent version. One thing that I noted is that I was forced to create /sessions and /outbox in my cache dir. And now I still see this error in the logs. 

[SentryAsyncConnection-0] throwable = [java.io.FileNotFoundException: https://www.MYSENTRYSERVER.com/api/2/envelope/], message = [Error while closing the connection.], args = [

**Steps to reproduce:**
- Use the app for a while. Force a crash

**Actual result:**
- Nothing shows in health metrics.

**Expected result:**
- Crash free users and other release health metrics should show up.

**Comment by marandaneto** [comment]
hey @carlosrivin thanks for raising this.

the `On-premise` version doesn't support the release health feature, yet.

the folders /sessions and /outbox are created automatically on SDK init.
See: https://github.com/getsentry/sentry-android/blob/master/sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java#L169

Do you mean that these folders were not created at all?

I'd suggest keeping the release feature disabled as it is by default and once On-premise is released, you enable it.

Thanks.

**Comment by carlosrivin** [comment]
Thanks for the reply @marandaneto 
The folders were not created automatically if you set manually the cache dir. But yeah. That part is fine. I just left it for it to automatically select the folders.
That's sad that it's not yet available. Can you help me find the onpremise plans to check when that will be released? Those metrics are essential for our migration to sentry.

**Comment by marandaneto** [comment]
@carlosrivin got it, yeah we create the folders on init based on the main cache dir, any reasons to not use the default one? just curiosity though.

I'm trying to get this information, I keep you posted.

**Comment by carlosrivin** [comment]
At my first trials to use the SDK I had to set a couple of extra parameters otherwise I would get some exceptions. So I just decided to go full manual. But recently I saw that this changed and now only setting the important stuff works so I removed all those properties. :)

Yes, please update me. :)

**Comment by carlosrivin** [comment]
@marandaneto  I created a similar ticket in the onpremise side and over there it seems that I have everything ok.
But I'm still getting this:
```
2020-06-11 16:16:19.396 D/Sentry: Envelope sent successfully.
2020-06-11 16:16:19.522 E/Sentry: Error while closing the connection.
    java.io.FileNotFoundException: https://sentryio.MYSERVER.com/api/2/envelope/
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
```
Could this be related to the not working release health metrics?

**Comment by marandaneto** [comment]
@carlosrivin can you link me the issue? I've got from them that it'll be only released in the next version.

**Comment by carlosrivin** [comment]
https://github.com/getsentry/onpremise/issues/533 this one @marandaneto

**Comment by marandaneto** [comment]
@carlosrivin thanks, I'll pass this down to the team, because it works on sentry.io so I believe there's no issues on the client-side (SDK).

**Comment by marandaneto** [comment]
I'll close this one as this is being tracked here https://github.com/getsentry/onpremise/issues/533
