### ISSUE TITLE
Line numbers not correctly using Proguard

### ISSUE THREAD

**Issue by PaulWoitaschek** [getsentry/sentry-android#455]
Using `AGP 4.0.0`, `sentry-android-core:2.1.6` and `sentry-android-gradle-plugin:1.7.34` and sentry onpremise 10.0.0, , the line numbers of the stack traces do not match and seem to always begin at line 1.
However the actual class names are de-obfuscated correctly.

I'm using sentry in parallel with firebase crashlytics and in firebase the line numbers show correctly.

**Comment by marandaneto** [comment]
hey @PaulWoitaschek thanks for raising this.
this is a dup of getsentry/sentry/pull/19012
we are aware and working on it, almost done, thanks for the patience.

**Comment by PaulWoitaschek** [comment]
Ah nice, thanks! I did not find this because there are so many issue trackers for so many components ;)
