### ISSUE TITLE
Be explicit by min API level

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-android#457]
- [ ] Add to `README.md` the min Android API supported.
- [x] Add tool to verify compatibility with such API

**Comment by marandaneto** [comment]
> * [ ]  Add tool to verify compatibility with such API

what type of tool do you mean? the android linter already breaks the build if it's not compatible with the minSdk.

**Comment by bruno-garcia** [comment]
So #458 isnt' needed since we always build the android lib which does the check. Even when we get to the monorepo with Java libraries, CI will build everything.

So we could just point out explicitly what's the min API we support on the README or on the docs.

**Comment by bruno-garcia** [comment]
Closed by #459
