### ISSUE TITLE
Non androidX project crash during build

### ISSUE THREAD

**Issue by Turbozanik** [getsentry/sentry-android#472]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion-28 /targetSdkVersion-28 /Build tools - 29.0.3) version?

_IDE:_
- [ ]  Android Studio -> Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 12
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: CheckStyle-IDEA, Dart, Statistic, com.google.services.firebase, com.konifar.material_icon_generator, io.flutter, nl.rubensten.texifyidea, org.plugin.dot.id

_Build system:_
- [ ]  Gradle -> 4.0.0

_Android Gradle Plugin:_
- [ ]  Yes -> wrapper gradle-6.1.1

_Sentry Android Gradle Plugin:_
- [ ]  Yes ->1.7.35

_Proguard/R8:_
- [ ]  Enabled

_sentry-android installed with:_
- [ ] Maven Central

The version of sentry-android:
2.2.0

---
I have the following issue:

I can't build my project after adding Sentry.
Error: “This project uses AndroidX dependencies”
1) It seems like sentry uses androidx dependencies in it and if project is not migrated to androidX we are unable to use sentry.
2) I couldn't find any information, that sentry requires android x. Is there a workaround for this, or maybe I have configured something wrong?
3) My build.gradle gist: https://gist.github.com/Turbozanik/23f021baaa595455f633dcff473d3570

**Steps to reproduce:**
- Just add sentry to the non androidx project and it will fail during installation.

**Actual result:**
Error: “This project uses AndroidX dependencies”

**Expected result:**
Build success.

**Comment by marandaneto** [comment]
Hey, you can remove it using gradle:


//    how to exclude androidx
//    implementation(project(":sentry-android")) {
//        exclude(group = "androidx.lifecycle", module = "lifecycle-process")
//        exclude(group = "androidx.lifecycle", module = "lifecycle-common-java8")
//    }

This is kotlin dsl but you can easily convert to groovy if necessary, i will add this to the docs btw, thanks.

**Comment by marandaneto** [comment]
docs will be fixed by https://github.com/getsentry/sentry-docs/pull/1805

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/android/#androidx-support
