### ISSUE TITLE
Support for multiple DSNs

### ISSUE THREAD

**Issue by andidev** [getsentry/sentry-android#485]
sentry-java had support for non static sentry clients with `SentryClientFactory.sentryClient()`. This is useful for 3rd-party libs. Is it possible to do with sentry-android as well? How can this be solved?

**Comment by marandaneto** [comment]
This is probably a dup of #393

There's some ongoing work to make this easier, see #473

**Comment by andidev** [comment]
@marandaneto 
Is there a workaround? 
I am a bit confused by by the issues about this.

Thanks for the quick answer!

**Comment by marandaneto** [comment]
@andidev the workaround is to follow the tips I've given #393 or just to wait for that feature to land and be released.

I don't have a full example though.
So it's technically possible with a little bit of code, but soon to be fixed.
