### ISSUE TITLE
Disabling automatic capture of fatal errors?

### ISSUE THREAD

**Issue by mshafrir-stripe** [getsentry/sentry-android#516]
Does the Sentry Android SDK have a mechanism to disable automatic capture of fatal errors?

**Comment by marandaneto** [comment]
what do you mean by automatic capture of fatal errors? if you say the Uncaught Exception handler, so yes:

https://github.com/getsentry/sentry-android/blob/master/sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml#L74-L75

or thru options.
https://github.com/getsentry/sentry-android/blob/a896e7ab88db52e002b4c6a489f5f2fea44af6e1/sentry-core/src/main/java/io/sentry/core/SentryOptions.java#L839-L846

**Comment by mshafrir-stripe** [comment]
@marandaneto thanks, this is exactly what I was looking for.
