### ISSUE TITLE
Method addObserver must be called on the main thread

### ISSUE THREAD

**Issue by lewisf** [getsentry/sentry-android#520]
**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**RN SDK version:** 1.6.3
**Android SDK version:** 2.2.0

**`react-native` version:** 0.62.17

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/persona-identities-inc/issues/1839866967/?project=5378601&query=is%3Aunresolved

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
**I have following issue:**

I went through barebones setup steps and am getting this error. Commenting out the `Sentry.init` gets rid of it. Stack trace seems to indicate it's all happening within the Sentry library but I'm not sure if I'm doing something wrong.

**Steps to reproduce:**
- New project on React Native 0.62.17
- Install Sentry
- Launch in Android Emulator using Pixel 2 API 29
- Red screen with error

**Actual result:**

![image](https://user-images.githubusercontent.com/588210/90283938-b8e77c00-de36-11ea-827b-cdc0cb5344c8.png)

**Expected result:**

No error.

**Comment by lewisf** [comment]
Thanks. Is there anything else I can do to help with debugging?

**Comment by zumaawad** [comment]
I have the same issue with react-native
```
    "react": "16.11.0",
    "react-native": "0.62.2",
    "@sentry/react-native": "^1.7.1"
```

**Comment by marandaneto** [comment]
hey thanks for reporting this, quick question:

are you initing the Android SDK manually by yourself or are you letting the Sentry RN SDK do the job automatically?

If you are letting the Sentry RN SDK do the job, on which life cycle (which class/method) of the RN App. are ou initing the Sentry RN SDK? thanks :)

**Comment by marandaneto** [comment]
@lewisf @zumaawad what version of the `androidx.lifecycle/lifecycle-process` lib are you working with btw? are you referencing directly or is it a transitive dependency? could you track this down, please? `2.2.0` doesn't have this check `enforceMainThreadIfNeeded` but maybe an older version have it.

**Comment by marandaneto** [comment]
as you can see, this has been changed in the lib and ideally, we'd add a main thread checker to avoid this problem.

1st commit: https://android.googlesource.com/platform/frameworks/support/+/1a587cf583809379add635a9047ded82d44306c8
2nd commit: https://android.googlesource.com/platform/frameworks/support/+/5675f1a128d0c3878ba97e74ef3aad521071a63b
3nd commit: https://android.googlesource.com/platform/frameworks/support/+/a9a8ffd7d455ff81f81f5c71bb300b6acab823ba

**Comment by marandaneto** [comment]
as a workaround, you can disable the lifecycle breadcrumbs for now:

https://docs.sentry.io/platforms/android/#default-context-for-android

```
<application>
    <!--     To disable the app lifecycle breadcrumbs integration-->
    <meta-data android:name="io.sentry.breadcrumbs.app-lifecycle" android:value="false" />
</application>
```

**Comment by zumaawad** [comment]
@marandaneto I'm using RN SDK and I initiate in app.js

**Comment by zumaawad** [comment]
@marandaneto Still the same

`E/unknown:ReactNative: Exception in native call
    java.lang.IllegalStateException: Method addObserver must be called on the main thread
        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
        at io.sentry.android.core.AppLifecycleIntegration.register(AppLifecycleIntegration.java:53)
        at io.sentry.core.Sentry.init(Sentry.java:159)
        at io.sentry.core.Sentry.init(Sentry.java:96)
        at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:59)
        at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:44)
        at io.sentry.RNSentryModule.startWithOptions(RNSentryModule.java:74)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
`

**Comment by marandaneto** [comment]
> @marandaneto Still the same
> 
> `E/unknown:ReactNative: Exception in native call java.lang.IllegalStateException: Method addObserver must be called on the main thread at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317) at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172) at io.sentry.android.core.AppLifecycleIntegration.register(AppLifecycleIntegration.java:53) at io.sentry.core.Sentry.init(Sentry.java:159) at io.sentry.core.Sentry.init(Sentry.java:96) at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:59) at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:44) at io.sentry.RNSentryModule.startWithOptions(RNSentryModule.java:74) at java.lang.reflect.Method.invoke(Native Method) at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) at android.os.Handler.handleCallback(Handler.java:883) at android.os.Handler.dispatchMessage(Handler.java:100) at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) at android.os.Looper.loop(Looper.java:214) at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) at java.lang.Thread.run(Thread.java:919) `

ups sorry, you also have to disable the session tracking as it depends on this 3rd party lib.

https://docs.sentry.io/platforms/react-native/#release-health

so if `enableAutoSessionTracking` is enabled, you've to disable it too, sorry about that.

**Comment by zumaawad** [comment]
@marandaneto Its working now with
`"@sentry/react-native": "^1.6.2"`
and 
`enableAutoSessionTracking` is disabled
and
`<application>
    
    <meta-data android:name="io.sentry.breadcrumbs.app-lifecycle" android:value="false" />
</application>`

**Comment by marandaneto** [comment]
@zumaawad good to know, mind answering the other question so we could choose the best solution? life cycle in the app.js file etc, thanks.

**Comment by billnbell** [comment]
I tried Sentry.init() in App.js and in index.android.js. Nothing helps.

**Comment by zumaawad** [comment]
> @zumaawad good to know, mind answering the other question so we could choose the best solution? life cycle in the app.js file etc, thanks.

In componentDidMount

**Comment by marandaneto** [comment]
@zumaawad have you tried right before the App ReactNode?

eg

```
import * as Sentry from '@sentry/react-native';

Sentry.init({ 
  dsn: '...',
  debug: true
});

const App: () => React$Node = () => {
  return (...)
}
```

**Comment by zumaawad** [comment]
@marandaneto I tired that too and didn’t work without workaround you mentioned before

**Comment by marandaneto** [comment]
@zumaawad ok, I will check if something has changed in the way how RN inits, we already have a PR to fix the issue anyway, getting feedback and will release a patch soon, thanks.

**Comment by zumaawad** [comment]
@marandaneto I think your PR https://github.com/getsentry/sentry-android/pull/525 will fix this

**Comment by marandaneto** [comment]
@zumaawad indeed, but I wanna find out the source of this issue, as we've not changed anything on this repo about that, its either a change on sentry-react-native or on RN itself.

**Comment by zumaawad** [comment]
@marandaneto The fun fact is: we didn’t change anything from our side too 😄 
Yes I think its related to android dependencies update

**Comment by marandaneto** [comment]
the Android SDK is published https://github.com/getsentry/sentry-android/releases/tag/2.3.1

you could upgrade this dependency in your `build.gradle` file or wait for a new version of the RN SDK which should come very soon as well.

path to upgrade the Android SDK:

something like: `{project}/node_modules/@sentry/react-native/android/build.gradle`
look for `io.sentry:sentry-android`

If you have applied the workarounds mentioned before, remember to revert it, so you don't lose the session tracking feature nor the app lifecycle breadcrumbs :)

**Comment by marandaneto** [comment]
RN SDK is also published https://github.com/getsentry/sentry-react-native/releases/tag/1.7.2

**Comment by zumaawad** [comment]
@marandaneto Thank you

**Comment by lewisf** [comment]
@marandaneto thanks!! appreciate the quick turnaround on this
