### ISSUE TITLE
Thread is marked as crashed when no exceptions are attached

### ISSUE THREAD

**Issue by maciejwalkowiak** [getsentry/sentry-android#524]
The version of sentry-android:
**2.x.x**

---
I have the following issue:

If `attachThreads` is set to `true` (default) if no exceptions are set on the event, current thread has crashed set to `true`.

`SentryThreadFactory.java`:

```java
final boolean crashed =
            (thread == currentThread)
                || (mechanismThreadIds != null && mechanismThreadIds.contains(thread.getId()));
```

According to test cases - this is an expected behaviour, but I am not sure what's the reasoning behind it:

`SentryThreadFactoryTest.java`:

```java
@Test
fun `when currentThreads is called, current thread is marked crashed`() {
    val sut = fixture.getSut()
    assertEquals(1, sut.getCurrentThreads(null)!!.filter { it.isCrashed }.count())
}
```

**Comment by marandaneto** [comment]
@maciejwalkowiak that's a wording problem in the protocol, `crashed` means: this is the thread that captured the event and not: this thread had an error or literally crashed/terminated or something like that.

we've been discussing about that and renaming would cause retro compatibility problems.

**Comment by maciejwalkowiak** [comment]
Understood. Thanks for clarification.

cc: @bruno-garcia puzzle solved
