### ISSUE TITLE
how to use fragment's name in breadcrumbs when using navigation component?

### ISSUE THREAD

**Issue by yangcheng** [getsentry/sentry-android#543]
_Platform:_
- [x]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version? all 28
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [x]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?  1.4.0 
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?

_IDE:_
- [x]  Android Studio -> If yes, which version?  4.0.1
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle -> If yes, which version? 6.3
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [x]  Yes -> If yes, which version? 4.0.1
- [ ]  No

_Sentry Android Gradle Plugin:_
- [x]  Yes -> If yes, which version? 
2.3.1
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled

_sentry-android installed with:_
- [x] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of sentry-android:
**2.3.1**

---
I have the following issue:
The breadcrumbs show only activity life cycle 
The description goes here ...

I am developing a single activity app using navigation component,  according to doc, single activity is a preferred pattern 
https://developer.android.com/guide/navigation/navigation-migrate

> To take full advantage of the Navigation component, your app should use multiple fragments in a single activity. 

My MainActivity;s layout.xml looks like 

```
    <androidx.fragment.app.FragmentContainerView
        android:id="@+id/nav_host_fragment"
        android:name="androidx.navigation.fragment.NavHostFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:defaultNavHost="true"
        android:theme="@style/AppTheme"
        app:navGraph="@navigation/nav_graph" />
```

**Steps to reproduce:**
- Step
initialize sentry SDK from gradle, keep all things default.  

**Actual result:**
- Actual
only activity lifecycle is shown

```
ui.lifecycle |  
-- | --
screen | MainActivity
state | stopped
```

**Expected result:**
- Result
breadcrumb show fragment life cyles events . `Screen` should show current fragment name.

**Comment by marandaneto** [comment]
@yangcheng thanks for your question.
we don't support that as this would require us adding the navigation component (androidx) libs as dependencies of the SDK.

you can track your own breadcrumbs manually https://docs.sentry.io/platforms/android/#breadcrumbs
there's probably a callback that you can track all the screen transitions or last case, add a breadcrumb in the first lifecycle of each of your fragment.
